apps/core/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home'),
]

apps/departamentos/urls.py
from django.urls import path
from .views import DepartamentosList, DepartamentosNovo, DepartamentoUpdate, DepartamentoDelete

urlpatterns = [
    path('list', DepartamentosList.as_view(), name= 'list_departamentos'),
    path('novo', DepartamentosNovo.as_view(), name= 'create_departamento'),
    path('update/<int:pk>/', DepartamentoUpdate.as_view(), name= 'update_departamento'),
    path('delete/<int:pk>/', DepartamentoDelete.as_view(), name='delete_departamento'),

]

apps/documentos/urls.py
from django.urls import path
from .views import DocumentoCreate

urlpatterns = [
    path('novo/<int:funcionario_id>/', DocumentoCreate.as_view(), name= 'create_documento'),
]

apps/empresas/urls.py
from django.urls import path
from .views import EmpresaCreate, EmpresaEdit


urlpatterns = [
    path('novo', EmpresaCreate.as_view(), name='create_empresa'),
    path('editar/<int:pk>', EmpresaEdit.as_view(), name='edit_empresa'),
]

apps/funcionarios/urls.py
from django.urls import path
from .views import  FuncionariosList, FuncionarioEdit, FuncionarioDelete,FuncionarioNovo

urlpatterns = [
    path('', FuncionariosList.as_view(), name= 'list_funcionarios'),
    path('novo/', FuncionarioNovo.as_view(), name= 'create_funcionario'),
    path('editar/<int:pk>/', FuncionarioEdit.as_view(), name= 'update_funcionario'),
    path('delete/<int:pk>/', FuncionarioDelete.as_view(), name= 'delete_funcionario'),
]

apps/registro_hora_extra/urls.py
from django.urls import path
from .views import  HoraExtraList

urlpatterns = [
    path('', HoraExtraList.as_view(), name= 'list_hora_extra'),
#    path('novo/', FuncionarioNovo.as_view(), name= 'create_funcionario'),
 #   path('editar/<int:pk>/', FuncionarioEdit.as_view(), name= 'update_funcionario'),
  #  path('delete/<int:pk>/', FuncionarioDelete.as_view(), name= 'delete_funcionario'),
]

gestao_rh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('empresa/', include('apps.empresas.urls')),
    path('documento/', include('apps.documentos.urls')),
    path('horas-extras/', include('apps.registro_hora_extra.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models

# Create your models here.

apps/departamentos/models.py
from django.db import models
from django.urls import reverse

from apps.empresas.models import Empresa


class Departamento(models.Model):
    nome = models.CharField(max_length=70)
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT)

    def get_absolute_url(self):
        return reverse('list_departamentos')

    def __str__(self):
        return self.nome

apps/documentos/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario


class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.pertence.id])

    def __str__(self):
        return self.descricao

apps/empresas/models.py
from django.db import models
from django.shortcuts import redirect


class Empresa(models.Model):
    nome = models.CharField(max_length=100, help_text='Nome da Empresa')

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return redirect('/')

apps/funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa


class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT)

    def get_absolute_url(self):
        return reverse('list_funcionarios')

    def __str__(self):
        return  self.nome

apps/registro_hora_extra/models.py
from django.db import models
from apps.funcionarios.models import Funcionario

class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    horas = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.motivo

apps/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from apps.funcionarios.models import Funcionario


@login_required
def home(request):
    data = {}
    data['usuario'] = request.user
    return render(request, 'index.html', data)

apps/departamentos/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Departamento

class DepartamentosList(ListView):
    model = Departamento

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Departamento.objects.filter(empresa=empresa_logada)


class DepartamentosNovo(CreateView):
    model = Departamento
    fields = ['nome']

    def form_valid(self, form):
        departamento = form.save(commit=False)
        departamento.empresa = self.request.user.funcionario.empresa
        departamento.save()
        return super(DepartamentosNovo, self).form_valid(form)

class DepartamentoUpdate(UpdateView):
    model = Departamento
    fields = ['nome']

class DepartamentoDelete(DeleteView):
    model = Departamento
    success_url = reverse_lazy('list_departamentos')

apps/documentos/views.py
from django.views.generic import CreateView
from .models import Documento

class DocumentoCreate(CreateView):
    model = Documento
    fields = ['descricao', 'arquivo']

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        form.instance.pertence_id = self.kwargs['funcionario_id']

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

apps/empresas/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView
from .models import Empresa


class EmpresaCreate(CreateView):
    model = Empresa
    fields = ['nome']

    def form_valid(self, form):
        obj = form.save()
        funcionario = self.request.user.funcionario
        funcionario.empresa = obj
        funcionario.save()
        return HttpResponse('ok')


class EmpresaEdit(UpdateView):
    model = Empresa
    fields = ['nome']

apps/funcionarios/views.py
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from .models import Funcionario
from django.views.generic import ListView, UpdateView, DeleteView, CreateView


class FuncionariosList(ListView):
    model = Funcionario
    template_name = 'funcionario_list.html'

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa_logada)

class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos']


class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_funcionarios')


class FuncionarioNovo(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos']

    def form_valid(self, form):
        funcionario = form.save(commit=False)
        username = funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1]
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionario.user = User.objects.create(username=username)
        funcionario.save()
        return super(FuncionarioNovo, self).form_valid(form)

apps/registro_hora_extra/views.py
from django.views.generic import ListView
from .models import RegistroHoraExtra


class HoraExtraList(ListView):
    model = RegistroHoraExtra

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return RegistroHoraExtra.objects.filter(funcionario__empresa=empresa_logada)

apps/core/templates/index.html
{% extends 'base.html' %}
{% block title %}Index{% endblock %}

{% block main %}<br>
<div class="row">
    <div class="col-sm">
      <h5>Curso UDEMY</h5>
    </div>
    <div class="col-sm">
     Olá {{ usuario.funcionario.nome }}<p>
        <a href="{% url 'list_funcionarios' %}">Gerenciar Funcionarios</a></p>
        <a href="{% url 'list_departamentos' %}">Gerenciar Departamentos</a><p></p>
        <a href="{% url 'list_hora_extra' %}">Gerenciar Banco de Horas</a>
    </div>
    <div class="col-sm">
        <a href="{% url 'logout' %}">Logout</a>  |

        {% if usuario.funcionario.empresa %}
            <a href="{% url 'edit_empresa' usuario.funcionario.empresa.pk %}">Editar Empresa</a>
        {% else %}
            <a href="{% url 'create_empresa' %}">Criar Empresa</a>
        {% endif %}
    </div>
  </div>
{% endblock %}

apps/departamentos/templates/departamentos/departamento_confirm_delete.html
{% extends 'base.html' %}

{% block main %}
   <h3>Deletar</h3>
<hr>
<form method="post">
{% csrf_token %}

   <div class="alert alert-danger" role="alert">
  <h4>Você esta certo que quer deletrar {{ obj }} ?</h4>
    </div>

    {{ form.as_p }}

    <button type="submit" class="btn btn-danger">Confirmar</button>
</form>

{% endblock%}

apps/departamentos/templates/departamentos/departamento_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block main %}<br>
   <h3>Novo Departamento</h3>

<form method="post">
{% csrf_token %}

    <div>
        {{ form|bootstrap_horizontal:'col-lg-7' }}
    </div>



    <br>
    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

{% endblock%}

apps/departamentos/templates/departamentos/departamento_list.html
{% extends 'base.html' %}

{% block main %}
   <h3>Lista de Departamentos</h3>
<hr>
<a class="btn btn-primary" href="{% url 'create_departamento' %}">+ Novo Departamento</a>
<hr>
    {% for departamento in object_list %}
    <ul>
        <li><a href="{% url 'update_departamento' departamento.pk %}">{{ departamento }}</a> |
            <a href="{% url 'delete_departamento' departamento.pk %}">Delete</a>
        </li>

    </ul>
    {% endfor %}

{% endblock%}

apps/documentos/templates/documentos/documento_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block main %}
<form method="post" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form|bootstrap_horizontal:'col-lg-7' }}<br>
    <button type="submit">Adicionar</button>

</form>

{% endblock %}

apps/empresas/templates/empresas/empresa_form.html
{% extends 'base.html' %}

{% block main %}
<form method="post">

    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>

</form>

{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block main %}
   <h3>Deletar</h3>
<hr>
<form method="post">
{% csrf_token %}

   <div class="alert alert-danger" role="alert">
  <h4>Você esta certo que quer deletrar {{ obj }} ?</h4>
    </div>

    {{ form }}

    <button type="submit" class="btn btn-danger">Confirmar</button>
</form>


{% endblock%}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block main %}

<br>

   <h3>Novo Funcionário</h3>


<form method="post">
{% csrf_token %}

    {{ form|bootstrap}}<br>

    <button type="submit" class="btn btn-primary">Salvar</button><p></p>
</form>
{% if object %}
<a href="{% url 'create_documento' object.id %}" class="btn btn-success">+Adicionar Documento</a><br>
{% endif %}
{% for documento in object.documento_set.all %}
        <a href="{{ documento.arquivo.url }}">{{ documento }}</a><br>
{% endfor %}
{% endblock%}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}

{% block main %}
   <h3>Lista de Funcionários</h3>
<hr>
<a class="btn btn-primary" href="{% url 'create_funcionario' %}">+ Novo funcionário</a>
<hr>
    {% for funcionario in object_list %}
    <ul>
        <li><a href="{% url 'update_funcionario' funcionario.pk %}">{{ funcionario.nome }}</a> |
            <a href="{% url 'delete_funcionario' funcionario.pk  %}">Delete</a>
        </li>

    </ul>
    {% endfor %}

{% endblock%}

apps/registro_hora_extra/templates/registro_hora_extra/registrohoraextra_list.html
{% extends 'base.html' %}

{% block main %}
   <h3>Banco de Horas</h3>

    {% for registro_re in object_list %}
        {{ registro_re }}<br>

    {% endfor %}

{% endblock%}

templates/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <div class="container">
        {% block main %} {% endblock %}
    </div>
</body>
</html>